name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 원격으로 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIMARY_KEY }}
          script: |
            export COMMIT_SHA="${{ github.sha }}";
            export REMOTE_USERNAME="${{ secrets.REMOTE_USERNAME }}"
            export MARIADB_PASSWORD="${{ secrets.MARIADB_PASSWORD }}"
            export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
            export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
            export COOLSMS_API_KEY="${{ secrets.COOLSMS_API_KEY }}"
            export COOLSMS_SECRET_KEY="${{ secrets.COOLSMS_SECRET_KEY }}"
            export COOLSMS_PHONE_NUMBER="${{ secrets.COOLSMS_PHONE_NUMBER }}"
            export ASSETS_SERVER_API_KEY="${{ secrets.ASSETS_SERVER_API_KEY }}"
            export TOSS_SECRET_KEY="${{ secrets.TOSS_SECRET_KEY }}"

            echo "$COMMIT_SHA 저장소 불러오기"
            cd /home/$REMOTE_USERNAME/isago
            git fetch origin main
            git reset --hard $COMMIT_SHA

            echo "환경 변수 파일 설정 중..."
            cp deploy.env .env
            envsubst < .env > .env.final
            mv .env.final .env

            echo "Redis 환경 설정 중..."
            cat > redis.conf <<EOF
            requirepass $REDIS_PASSWORD
            EOF

            sudo npm i --force
            sudo npm run build
            sudo npm run docker:1

            PREV_COMMIT=${{ github.event.workflow_run.head_commit.id }}^
            CURR_COMMIT=${{ github.event.workflow_run.head_commit.id }}

            # 변경된 파일 목록에서 liquibase 관련 파일이 있는지 확인.
            if git diff --name-only "$PREV_COMMIT" "$CURR_COMMIT" | grep -q '^liquibase/'; then
              echo "🔄 liquibase 관련 코드에 대한 변경이 감지되었습니다."
              sudo npx pm2 kill
              echo "MariaDB와 Redis가 완전히 초기화될 때까지 대기 중..."
              while \
                [ "$(docker inspect -f '{{.State.Health.Status}}' MariaDB)" != "healthy" ] || \
                [ "$(docker inspect -f '{{.State.Health.Status}}' Redis)" != "healthy" ]; do
                sleep 1
              done
              sudo npm run docker:2
              sudo npm run serve
            else
              echo "✅ liquibase 관련 코드에 대한 변경이 없습니다."
              sudo npm run reserve
            fi

            echo "🚀 자동화 배포가 완료되었습니다."